import type { Feature, PricingTier, TeamMember, Step, NavLink } from '@/lib/marketing/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Features', href: '#features' },
  { label: 'Stockman IQ', href: '#stockman-iq' },
  { label: 'Advisors', href: '#advisors' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'About', href: '#about' },
]

export const FEATURES: Feature[] = [
  {
    id: 'portfolio-dashboard',
    name: 'Portfolio Dashboard',
    description: 'See your total livestock portfolio value at a glance. Live market data updates your herds automatically, so you always know what your cattle are worth.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: ['Live market pricing', 'Performance charts with time-range scrubbing', 'Capital concentration breakdown'],
    icon: 'chart',
  },
  {
    id: 'herd-management',
    name: 'Herd Management',
    description: 'Add and manage your livestock herds as financial assets. Track head count, weight, daily weight gain, breeding details, and sell stock with full pricing analysis.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: ['Cattle, sheep, pigs, and goats', 'Breeding and calving tracking', 'CSV import for bulk entry'],
    icon: 'cattle',
  },
  {
    id: 'stockman-iq',
    name: 'Stockman IQ',
    description: 'AI-powered capital timing intelligence. Get plain-English insights on the best month, weight, and market to maximise returns on your herds.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: ['Best sale month and weight alignment', 'Sell vs hold analysis', 'Market comparison net of freight'],
    icon: 'brain',
  },
  {
    id: 'yard-book',
    name: 'Yard Book',
    description: 'An integrated farm operations calendar. Schedule musters, vaccinations, breeding, sales, and any farm task with push notification reminders.',
    accentColor: '#87B11B',
    accentColorLight: '#A3CC3D',
    bullets: ['NLP event creation via Brangus', 'Herd-linked events', 'Customisable reminders and recurrence'],
    icon: 'calendar',
  },
  {
    id: 'freight-iq',
    name: 'Freight IQ',
    description: 'Estimate livestock transport costs using industry-standard loading densities and real driving distances. Know what freight will cost before you commit.',
    accentColor: '#1399EC',
    accentColorLight: '#64BBF5',
    bullets: ['11 transport categories', 'Real driving distances via Apple Maps', 'Per head, per deck, and total cost breakdown'],
    icon: 'truck',
  },
  {
    id: 'grid-iq',
    name: 'Grid IQ',
    description: 'Compare market prices against processor grids with freight and kill history factored in. Upload grids via camera and let AI extract the data.',
    accentColor: '#00B4A0',
    accentColorLight: '#33D4C0',
    bullets: ['AI grid extraction from photos/PDF', 'Three-layer price comparison', 'Processor fit scoring'],
    icon: 'grid',
  },
  {
    id: 'reports',
    name: 'Professional Reports',
    description: 'Generate bank-ready, accountant-ready PDF reports with a tap. Asset registers, sales summaries, and market comparisons, branded and professional.',
    accentColor: '#D4A053',
    accentColorLight: '#E8C07A',
    bullets: ['Asset Register and Sales Summary', 'Accounting Report', 'Share via email or AirDrop'],
    icon: 'document',
  },
  {
    id: 'advisor-workspace',
    name: 'Advisor Workspace',
    description: 'Purpose-built tools for bankers, agents, and accountants. Apply private valuation overlays, run scenarios, and generate professional reports for clients.',
    accentColor: '#B0657A',
    accentColorLight: '#CC8E9F',
    bullets: ['Advisor Lens with shading slider', 'Time-limited client permissions', 'What-if simulator sandbox'],
    icon: 'briefcase',
  },
]

export const HOW_IT_WORKS_STEPS: Step[] = [
  {
    number: 1,
    title: 'Add your herds',
    description: 'Enter your livestock details: species, breed, head count, and weight. Import from CSV or add manually. Set up your properties and assign markets.',
  },
  {
    number: 2,
    title: 'Get real-time valuations',
    description: 'Live market data prices your herds automatically. Watch your portfolio value update daily with breeding accruals, weight gain projections, and mortality adjustments.',
  },
  {
    number: 3,
    title: 'Make smarter decisions',
    description: 'AI-powered insights tell you when to sell, where to sell, and what you will net after freight. Generate professional reports for the bank or your accountant.',
  },
]

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'stockman',
    name: 'Stockman',
    subtitle: 'Single Property',
    price: null,
    priceAnnual: null,
    description: 'For operators managing a single farm.',
    highlighted: false,
    features: [
      { name: '1 property', included: true },
      { name: 'Unlimited herds', included: true },
      { name: 'Live market pricing', included: true },
      { name: '50 Brangus AI queries/month', included: true },
      { name: '5 freight calculations/month', included: true },
      { name: 'Yard Book with reminders', included: true },
      { name: 'Core reports (Asset Register, Sales, Accounting)', included: true },
      { name: 'Grid IQ', included: false },
      { name: 'CSV import', included: false },
    ],
  },
  {
    id: 'head-stockman',
    name: 'Head Stockman',
    subtitle: 'Multi Property',
    price: null,
    priceAnnual: null,
    description: 'For operators managing livestock across multiple farms as a portfolio.',
    highlighted: true,
    badge: 'Most Popular',
    features: [
      { name: 'Unlimited properties', included: true },
      { name: 'Unlimited herds', included: true },
      { name: 'Live market pricing', included: true },
      { name: '150 Brangus AI queries/month', included: true },
      { name: '15 freight calculations/month', included: true },
      { name: 'Grid IQ processor analysis', included: true },
      { name: 'CSV import', included: true },
      { name: 'Herd Scenario Simulator', included: true },
      { name: 'All reports including Market Comparison', included: true },
    ],
  },
  {
    id: 'advisor',
    name: 'Advisor',
    subtitle: 'Professional',
    price: null,
    priceAnnual: null,
    description: 'For agribusiness bankers, livestock agents, accountants, and insurers.',
    highlighted: false,
    features: [
      { name: 'Up to 10 active clients', included: true },
      { name: 'Advisor Lens overlays', included: true },
      { name: 'Named scenarios (Conservative, Bank Policy, Custom)', included: true },
      { name: '100 Brangus AI queries/month', included: true },
      { name: '10 freight calculations/month', included: true },
      { name: 'What-if Simulator sandbox', included: true },
      { name: 'Time-limited client permissions', included: true },
      { name: 'Advisor valuation reports', included: true },
      { name: 'Unlimited clients', included: false },
    ],
  },
  {
    id: 'head-advisor',
    name: 'Head Advisor',
    subtitle: 'Enterprise',
    price: null,
    priceAnnual: null,
    description: 'For firms and practices managing a larger client book.',
    highlighted: false,
    features: [
      { name: 'Unlimited active clients', included: true },
      { name: 'Everything in Advisor', included: true },
      { name: '250 Brangus AI queries/month', included: true },
      { name: '25 freight calculations/month', included: true },
      { name: 'All premium reports', included: true },
      { name: 'Dedicated onboarding support', included: true },
      { name: 'Priority support', included: true },
    ],
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Luke St. George',
    role: 'Chief Executive Officer',
    email: 'luke@stockmanswallet.com.au',
    bio: 'Leading the vision for capital intelligence in Australian agriculture.',
  },
  {
    name: 'Mil Jayaratne',
    role: 'Chief Operating Officer',
    email: 'mil@stockmanswallet.com.au',
    bio: 'Driving operations and strategy to bring Stockman\'s Wallet to market.',
  },
  {
    name: 'Leon Ernst',
    role: 'Chief Technology Officer',
    email: 'leon@stockmanswallet.com.au',
    bio: 'Building the technology that powers intelligent livestock valuation.',
  },
]
