import type { Feature, PricingTier, TeamMember, Step, NavLink } from '@/lib/marketing/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Features', href: '#features' },
  { label: 'Stockman IQ', href: '#stockman-iq' },
  { label: 'Advisors', href: '#advisors' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'About', href: '#about' },
]

export const FEATURES: Feature[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'View your total livestock portfolio in one place. Track live market-linked pricing, monitor performance over time, and understand where your capital is concentrated across the herd.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: [
      'See your total livestock portfolio value update in real time',
      'Track live market-linked pricing across every herd',
      'Monitor performance over time with interactive charts',
      'Understand capital concentration across herd groups and properties',
      'Get a clear financial snapshot of your entire operation at a glance',
    ],
    icon: 'chart',
  },
  {
    id: 'herd-valuation',
    name: 'Herd Valuation',
    description: 'Turn each herd into a live financial asset. Market-linked valuations reflect breed premiums, daily weight gain, breeding activity, and projected biological change, so your balance sheet keeps pace with the paddock.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: [
      'Add and manage herds as financial assets within your portfolio',
      'Match each herd to live market data with breed premium adjustments',
      'Capture core herd inputs including headcount, weight, age, and class',
      'Track breeding activity, calving rates, and pre-birth accruals across relevant herds',
      'Apply growth and mortality assumptions to project changing herd values over time',
    ],
    icon: 'cattle',
  },
  {
    id: 'reports',
    name: 'Reports',
    description: 'Generate professional reports your bank manager, accountant, or advisor can actually use. Asset registers, sales summaries, and branded valuation reports, filtered by date range and property, exported as PDF or shared via email.',
    accentColor: '#D4A053',
    accentColorLight: '#E8C07A',
    bullets: [
      'Build asset registers with full herd-by-herd valuations and price source tracking',
      'Generate accountant-ready summaries with portfolio overview, composition, and sales history',
      'Filter by date range and property for precise reporting periods',
      'Export branded PDF reports or share directly via email',
      'Track sales performance with gross, freight, and net breakdowns',
    ],
    icon: 'document',
  },
  {
    id: 'advisory-hub',
    name: 'Advisory Hub',
    description: 'Give your banker, agent, accountant, or insurer a window into your portfolio, on your terms. Advisors request time-limited access, you approve or deny, and they get read-only tools purpose-built for professional analysis.',
    accentColor: '#B0657A',
    accentColorLight: '#CC8E9F',
    bullets: [
      'Grant time-limited, read-only portfolio access to trusted advisors',
      'Approve or deny access requests with a 3-day approval window',
      'Advisors get dedicated tools including valuation overlays and scenario modelling',
      'Browse a directory of advisors by role, company, and region',
      'Keep full control and revoke access at any time',
    ],
    icon: 'briefcase',
  },
  {
    id: 'yard-book',
    name: 'Yard Book',
    description: 'Your digital run sheet. Track every mustering, vet visit, breeding event, maintenance job, and personal reminder in one place, with colour-coded categories, recurring schedules, and horizon-based grouping so nothing falls through the cracks.',
    accentColor: '#87B11B',
    accentColorLight: '#A3CC3D',
    bullets: [
      'Create events across five categories: Health, Mustering, Maintenance, Breeding, and Admin',
      'Set recurring schedules and reminder offsets so you are always ahead',
      'Link events to one or more herds for full operational context',
      'View tasks grouped by horizon: Overdue, Today, Next 7 Days, Next 30, and beyond',
      'Mark items complete and track progress across your operation',
    ],
    icon: 'calendar',
  },
  {
    id: 'freight-iq',
    name: 'Freight IQ',
    description: 'Estimate transport costs before you commit cattle to market. Industry-standard loading densities, real driving distances, and full cost breakdowns so you can compare markets net of freight and find the best return.',
    accentColor: '#1399EC',
    accentColorLight: '#64BBF5',
    bullets: [
      '11 transport categories with weight-based escalation pricing',
      'Real driving distances calculated via Apple Maps',
      'Per-head, per-deck, and total cost breakdown including GST',
      'Save estimates for future reference and side-by-side comparison',
      'Feed results into Grid IQ for net-of-freight market vs processor analysis',
    ],
    icon: 'truck',
  },
  {
    id: 'producer-network',
    name: 'Producer Network',
    description: 'Connect with other producers in your region. Build a trusted peer network to share operational insights, compare notes on markets and conditions, and collaborate on the challenges only another farmer understands.',
    accentColor: '#7C6DD8',
    accentColorLight: '#A094E8',
    bullets: [
      'Browse a directory of producers and send connection requests',
      'Build a permanent network of trusted peers across your region',
      'Message connections directly with thread-based chat',
      'Share insights on markets, conditions, and service providers',
      'Control your visibility and opt in or out of the producer directory',
    ],
    icon: 'globe',
  },
  {
    id: 'grid-iq',
    name: 'Grid IQ',
    description: 'Compare the saleyard against the processor before you sell. Upload grids via photo or PDF, let AI extract the data, build a test consignment from your portfolio, and see which channel nets the best return. Then track kill sheets to sharpen future decisions.',
    accentColor: '#00B4A0',
    accentColorLight: '#33D4C0',
    bullets: [
      'AI-powered grid extraction from photos, PDFs, and spreadsheets',
      'Net market vs net processor comparison including freight',
      'Processor fit scoring and sell window indicator per category',
      'Post-kill analysis with Grid Capture Ratio, Realisation Factor, and Kill Score',
      'Build a kill sheet library that improves your predictions over time',
    ],
    icon: 'grid',
  },
  {
    id: 'markets',
    name: 'Markets',
    description: 'Live MLA market data at your fingertips. National indicators, saleyard category prices, and trend signals, updated daily so you can time your decisions with confidence.',
    accentColor: '#E8594E',
    accentColorLight: '#F08070',
    bullets: [
      'National price indicators for beef cattle, sheep, pigs, and goats with trend signals',
      'Saleyard category prices aggregated across Australian markets',
      'Track price movements over time by category and region',
      'Spot trends early with up, down, and flat market signals',
      'Data feeds directly into your portfolio valuations and insight engine',
    ],
    icon: 'trending',
  },
  {
    id: 'insights',
    name: 'Insights',
    description: 'Your AI stock advisor evaluates your portfolio every day against live market conditions and surfaces the calls that matter. Sell vs hold, optimal timing, weight targets, best market, price sensitivity, and calving forecasts.',
    accentColor: '#D9762F',
    accentColorLight: '#F4A871',
    bullets: [
      'Daily AI evaluation of your portfolio against current market data',
      'Sell vs hold analysis with projected gains over 30, 60, and 90 days',
      'Optimal sale month identification based on historical seasonal pricing',
      'Calving forecasts tracking gestation progress and expected calf value',
      'Yard Book alerts surfacing overdue and upcoming tasks',
    ],
    icon: 'brain',
  },
]

export const HOW_IT_WORKS_STEPS: Step[] = [
  {
    number: 1,
    title: 'Add your herds',
    description: 'Enter your livestock details: species, breed, head count, and weight. Import from CSV or add manually. Set up your properties and assign markets.',
  },
  {
    number: 2,
    title: 'Get real-time valuations',
    description: 'Live market data prices your herds automatically. Watch your portfolio value update daily with breeding accruals, weight gain projections, and mortality adjustments.',
  },
  {
    number: 3,
    title: 'Make smarter decisions',
    description: 'AI-powered insights tell you when to sell, where to sell, and what you will net after freight. Generate professional reports for the bank or your accountant.',
  },
]

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'stockman',
    name: 'Stockman',
    subtitle: 'Single Property',
    price: null,
    priceAnnual: null,
    description: 'For operators managing a single farm.',
    highlighted: false,
    features: [
      { name: '1 property', included: true },
      { name: 'Unlimited herds', included: true },
      { name: 'Live market pricing', included: true },
      { name: '50 Brangus AI queries/month', included: true },
      { name: '5 freight calculations/month', included: true },
      { name: 'Yard Book with reminders', included: true },
      { name: 'Core reports (Asset Register, Sales, Accounting)', included: true },
      { name: 'Grid IQ', included: false },
      { name: 'CSV import', included: false },
    ],
  },
  {
    id: 'head-stockman',
    name: 'Head Stockman',
    subtitle: 'Multi Property',
    price: null,
    priceAnnual: null,
    description: 'For operators managing livestock across multiple farms as a portfolio.',
    highlighted: true,
    badge: 'Most Popular',
    features: [
      { name: 'Unlimited properties', included: true },
      { name: 'Unlimited herds', included: true },
      { name: 'Live market pricing', included: true },
      { name: '150 Brangus AI queries/month', included: true },
      { name: '15 freight calculations/month', included: true },
      { name: 'Grid IQ processor analysis', included: true },
      { name: 'CSV import', included: true },
      { name: 'Herd Scenario Simulator', included: true },
      { name: 'All reports including Market Comparison', included: true },
    ],
  },
  {
    id: 'advisor',
    name: 'Advisor',
    subtitle: 'Professional',
    price: null,
    priceAnnual: null,
    description: 'For agribusiness bankers, livestock agents, accountants, and insurers.',
    highlighted: false,
    features: [
      { name: 'Up to 10 active clients', included: true },
      { name: 'Advisor Lens overlays', included: true },
      { name: 'Named scenarios (Conservative, Bank Policy, Custom)', included: true },
      { name: '100 Brangus AI queries/month', included: true },
      { name: '10 freight calculations/month', included: true },
      { name: 'What-if Simulator sandbox', included: true },
      { name: 'Time-limited client permissions', included: true },
      { name: 'Advisor valuation reports', included: true },
      { name: 'Unlimited clients', included: false },
    ],
  },
  {
    id: 'head-advisor',
    name: 'Head Advisor',
    subtitle: 'Enterprise',
    price: null,
    priceAnnual: null,
    description: 'For firms and practices managing a larger client book.',
    highlighted: false,
    features: [
      { name: 'Unlimited active clients', included: true },
      { name: 'Everything in Advisor', included: true },
      { name: '250 Brangus AI queries/month', included: true },
      { name: '25 freight calculations/month', included: true },
      { name: 'All premium reports', included: true },
      { name: 'Dedicated onboarding support', included: true },
      { name: 'Priority support', included: true },
    ],
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Luke St. George',
    role: 'Chief Executive Officer',
    email: 'luke@stockmanswallet.com.au',
    bio: 'Leading the vision for capital intelligence in Australian agriculture.',
  },
  {
    name: 'Mil Jayaratne',
    role: 'Chief Operating Officer',
    email: 'mil@stockmanswallet.com.au',
    bio: 'Driving operations and strategy to bring Stockman\'s Wallet to market.',
  },
  {
    name: 'Leon Ernst',
    role: 'Chief Technology Officer',
    email: 'leon@stockmanswallet.com.au',
    bio: 'Building the technology that powers intelligent livestock valuation.',
  },
]
