// Supabase database types — Row, Insert, Update for each table
// Matches supabase/migrations/20260304100001_user_data_sync_tables.sql

export type Database = {
  public: {
    Tables: {
      properties: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
          property_name: string;
          property_pic: string | null;
          is_default: boolean;
          is_simulated: boolean;
          state: string;
          region: string | null;
          address: string | null;
          suburb: string | null;
          postcode: string | null;
          latitude: number | null;
          longitude: number | null;
          acreage: number | null;
          property_type: string | null;
          notes: string | null;
          default_saleyard: string | null;
          default_saleyard_distance: number | null;
          mortality_rate: number;
          calving_rate: number;
          freight_cost_per_km: number;
          is_deleted: boolean;
          deleted_at: string | null;
          last_synced_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
          property_name: string;
          property_pic?: string | null;
          is_default?: boolean;
          is_simulated?: boolean;
          state: string;
          region?: string | null;
          address?: string | null;
          suburb?: string | null;
          postcode?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          acreage?: number | null;
          property_type?: string | null;
          notes?: string | null;
          default_saleyard?: string | null;
          default_saleyard_distance?: number | null;
          mortality_rate?: number;
          calving_rate?: number;
          freight_cost_per_km?: number;
          is_deleted?: boolean;
          deleted_at?: string | null;
          last_synced_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
          property_name?: string;
          property_pic?: string | null;
          is_default?: boolean;
          is_simulated?: boolean;
          state?: string;
          region?: string | null;
          address?: string | null;
          suburb?: string | null;
          postcode?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          acreage?: number | null;
          property_type?: string | null;
          notes?: string | null;
          default_saleyard?: string | null;
          default_saleyard_distance?: number | null;
          mortality_rate?: number;
          calving_rate?: number;
          freight_cost_per_km?: number;
          is_deleted?: boolean;
          deleted_at?: string | null;
          last_synced_at?: string | null;
        };
      };
      herds: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
          name: string;
          animal_id_number: string | null;
          species: "Cattle" | "Sheep" | "Pig" | "Goat";
          breed: string;
          sex: "Male" | "Female";
          category: string;
          age_months: number;
          head_count: number;
          initial_weight: number;
          current_weight: number;
          daily_weight_gain: number;
          dwg_change_date: string | null;
          previous_dwg: number | null;
          use_creation_date_for_weight: boolean;
          is_breeder: boolean;
          is_pregnant: boolean;
          joined_date: string | null;
          calving_rate: number;
          lactation_status: string | null;
          calving_processed_date: string | null;
          breeding_program_type: "ai" | "controlled" | "uncontrolled" | null;
          joining_period_start: string | null;
          joining_period_end: string | null;
          selected_saleyard: string | null;
          sub_category: string | null;
          breeder_sub_type: string | null;
          validation_status: string | null;
          is_sold: boolean;
          sold_date: string | null;
          sold_price: number | null;
          paddock_name: string | null;
          location_latitude: number | null;
          location_longitude: number | null;
          property_id: string | null;
          breed_premium_override: number | null;
          additional_info: string | null;
          notes: string | null;
          mortality_rate: number | null;
          calf_weight_recorded_date: string | null;
          is_demo_data: boolean;
          is_deleted: boolean;
          deleted_at: string | null;
          last_synced_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          animal_id_number?: string | null;
          species: "Cattle" | "Sheep" | "Pig" | "Goat";
          breed: string;
          sex: "Male" | "Female";
          category: string;
          age_months?: number;
          head_count?: number;
          initial_weight?: number;
          current_weight?: number;
          daily_weight_gain?: number;
          dwg_change_date?: string | null;
          previous_dwg?: number | null;
          use_creation_date_for_weight?: boolean;
          is_breeder?: boolean;
          is_pregnant?: boolean;
          joined_date?: string | null;
          calving_rate?: number;
          lactation_status?: string | null;
          calving_processed_date?: string | null;
          breeding_program_type?: "ai" | "controlled" | "uncontrolled" | null;
          joining_period_start?: string | null;
          joining_period_end?: string | null;
          selected_saleyard?: string | null;
          sub_category?: string | null;
          breeder_sub_type?: string | null;
          validation_status?: string | null;
          is_sold?: boolean;
          sold_date?: string | null;
          sold_price?: number | null;
          paddock_name?: string | null;
          location_latitude?: number | null;
          location_longitude?: number | null;
          property_id?: string | null;
          breed_premium_override?: number | null;
          additional_info?: string | null;
          notes?: string | null;
          mortality_rate?: number | null;
          calf_weight_recorded_date?: string | null;
          is_demo_data?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          last_synced_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          animal_id_number?: string | null;
          species?: "Cattle" | "Sheep" | "Pig" | "Goat";
          breed?: string;
          sex?: "Male" | "Female";
          category?: string;
          age_months?: number;
          head_count?: number;
          initial_weight?: number;
          current_weight?: number;
          daily_weight_gain?: number;
          dwg_change_date?: string | null;
          previous_dwg?: number | null;
          use_creation_date_for_weight?: boolean;
          is_breeder?: boolean;
          is_pregnant?: boolean;
          joined_date?: string | null;
          calving_rate?: number;
          lactation_status?: string | null;
          calving_processed_date?: string | null;
          breeding_program_type?: "ai" | "controlled" | "uncontrolled" | null;
          joining_period_start?: string | null;
          joining_period_end?: string | null;
          selected_saleyard?: string | null;
          sub_category?: string | null;
          breeder_sub_type?: string | null;
          validation_status?: string | null;
          is_sold?: boolean;
          sold_date?: string | null;
          sold_price?: number | null;
          paddock_name?: string | null;
          location_latitude?: number | null;
          location_longitude?: number | null;
          property_id?: string | null;
          breed_premium_override?: number | null;
          additional_info?: string | null;
          notes?: string | null;
          mortality_rate?: number | null;
          calf_weight_recorded_date?: string | null;
          is_demo_data?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          last_synced_at?: string | null;
        };
      };
      muster_records: {
        Row: {
          id: string;
          user_id: string;
          herd_id: string;
          created_at: string;
          date: string;
          notes: string | null;
          total_head_count: number | null;
          cattle_yard: string | null;
          weaners_count: number | null;
          branders_count: number | null;
          is_demo_data: boolean;
          linked_yard_book_item_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          herd_id: string;
          created_at?: string;
          date: string;
          notes?: string | null;
          total_head_count?: number | null;
          cattle_yard?: string | null;
          weaners_count?: number | null;
          branders_count?: number | null;
          is_demo_data?: boolean;
          linked_yard_book_item_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          herd_id?: string;
          created_at?: string;
          date?: string;
          notes?: string | null;
          total_head_count?: number | null;
          cattle_yard?: string | null;
          weaners_count?: number | null;
          branders_count?: number | null;
          is_demo_data?: boolean;
          linked_yard_book_item_id?: string | null;
        };
      };
      health_records: {
        Row: {
          id: string;
          user_id: string;
          herd_id: string;
          created_at: string;
          date: string;
          treatment_type: "Vaccination" | "Drenching" | "Parasite Treatment" | "Other";
          notes: string | null;
          is_demo_data: boolean;
          linked_yard_book_item_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          herd_id: string;
          created_at?: string;
          date: string;
          treatment_type: "Vaccination" | "Drenching" | "Parasite Treatment" | "Other";
          notes?: string | null;
          is_demo_data?: boolean;
          linked_yard_book_item_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          herd_id?: string;
          created_at?: string;
          date?: string;
          treatment_type?: "Vaccination" | "Drenching" | "Parasite Treatment" | "Other";
          notes?: string | null;
          is_demo_data?: boolean;
          linked_yard_book_item_id?: string | null;
        };
      };
      sales_records: {
        Row: {
          id: string;
          user_id: string;
          herd_id: string;
          created_at: string;
          sale_date: string;
          head_count: number;
          average_weight: number;
          price_per_kg: number;
          price_per_head: number | null;
          pricing_type: "per_kg" | "per_head";
          sale_type: string | null;
          sale_location: string | null;
          total_gross_value: number;
          freight_cost: number;
          freight_distance: number;
          net_value: number;
          notes: string | null;
          pdf_path: string | null;
          is_demo_data: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          herd_id: string;
          created_at?: string;
          sale_date: string;
          head_count: number;
          average_weight: number;
          price_per_kg: number;
          price_per_head?: number | null;
          pricing_type?: "per_kg" | "per_head";
          sale_type?: string | null;
          sale_location?: string | null;
          total_gross_value: number;
          freight_cost?: number;
          freight_distance?: number;
          net_value: number;
          notes?: string | null;
          pdf_path?: string | null;
          is_demo_data?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          herd_id?: string;
          created_at?: string;
          sale_date?: string;
          head_count?: number;
          average_weight?: number;
          price_per_kg?: number;
          price_per_head?: number | null;
          pricing_type?: "per_kg" | "per_head";
          sale_type?: string | null;
          sale_location?: string | null;
          total_gross_value?: number;
          freight_cost?: number;
          freight_distance?: number;
          net_value?: number;
          notes?: string | null;
          pdf_path?: string | null;
          is_demo_data?: boolean;
        };
      };
      yard_book_items: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
          title: string;
          notes: string | null;
          event_date: string;
          is_all_day: boolean;
          event_time: string | null;
          category_raw: "Livestock" | "Operations" | "Finance" | "Family" | "Me";
          is_completed: boolean;
          completed_date: string | null;
          is_recurring: boolean;
          recurrence_rule_raw: "Weekly" | "Fortnightly" | "Monthly" | "Annual" | null;
          recurrence_interval: number | null;
          reminder_offsets: number[] | null;
          notifications_scheduled: boolean;
          linked_herd_ids: string[] | null;
          property_id: string | null;
          pack_id: string | null;
          pack_item_index: number | null;
          is_demo_data: boolean;
          is_deleted: boolean;
          deleted_at: string | null;
          linked_muster_record_id: string | null;
          linked_health_record_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
          title: string;
          notes?: string | null;
          event_date: string;
          is_all_day?: boolean;
          event_time?: string | null;
          category_raw?: "Livestock" | "Operations" | "Finance" | "Family" | "Me";
          is_completed?: boolean;
          completed_date?: string | null;
          is_recurring?: boolean;
          recurrence_rule_raw?: "Weekly" | "Fortnightly" | "Monthly" | "Annual" | null;
          recurrence_interval?: number | null;
          reminder_offsets?: number[] | null;
          notifications_scheduled?: boolean;
          linked_herd_ids?: string[] | null;
          property_id?: string | null;
          pack_id?: string | null;
          pack_item_index?: number | null;
          is_demo_data?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          linked_muster_record_id?: string | null;
          linked_health_record_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
          title?: string;
          notes?: string | null;
          event_date?: string;
          is_all_day?: boolean;
          event_time?: string | null;
          category_raw?: "Livestock" | "Operations" | "Finance" | "Family" | "Me";
          is_completed?: boolean;
          completed_date?: string | null;
          is_recurring?: boolean;
          recurrence_rule_raw?: "Weekly" | "Fortnightly" | "Monthly" | "Annual" | null;
          recurrence_interval?: number | null;
          reminder_offsets?: number[] | null;
          notifications_scheduled?: boolean;
          linked_herd_ids?: string[] | null;
          property_id?: string | null;
          pack_id?: string | null;
          pack_item_index?: number | null;
          is_demo_data?: boolean;
          is_deleted?: boolean;
          deleted_at?: string | null;
          linked_muster_record_id?: string | null;
          linked_health_record_id?: string | null;
        };
      };
      kill_sheet_records: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          processor_name: string;
          grid_code: string | null;
          kill_date: string;
          vendor_code: string | null;
          pic: string | null;
          property_name: string | null;
          booking_reference: string | null;
          booking_type: string | null;
          herd_id: string | null;
          total_head_count: number;
          total_body_weight: number;
          total_gross_value: number;
          average_body_weight: number;
          average_price_per_kg: number;
          average_value_per_head: number;
          condemns: number;
          category_summaries: unknown;
          grade_distribution: unknown;
          weight_class_distribution: unknown;
          fat_class_distribution: unknown;
          line_items: unknown;
          realisation_factor: number | null;
          payment_check_result: unknown | null;
          source_file_path: string | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          processor_name: string;
          grid_code?: string | null;
          kill_date: string;
          vendor_code?: string | null;
          pic?: string | null;
          property_name?: string | null;
          booking_reference?: string | null;
          booking_type?: string | null;
          herd_id?: string | null;
          total_head_count: number;
          total_body_weight: number;
          total_gross_value: number;
          average_body_weight: number;
          average_price_per_kg: number;
          average_value_per_head: number;
          condemns?: number;
          category_summaries?: unknown;
          grade_distribution?: unknown;
          weight_class_distribution?: unknown;
          fat_class_distribution?: unknown;
          line_items?: unknown;
          realisation_factor?: number | null;
          payment_check_result?: unknown | null;
          source_file_path?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          processor_name?: string;
          grid_code?: string | null;
          kill_date?: string;
          vendor_code?: string | null;
          pic?: string | null;
          property_name?: string | null;
          booking_reference?: string | null;
          booking_type?: string | null;
          herd_id?: string | null;
          total_head_count?: number;
          total_body_weight?: number;
          total_gross_value?: number;
          average_body_weight?: number;
          average_price_per_kg?: number;
          average_value_per_head?: number;
          condemns?: number;
          category_summaries?: unknown;
          grade_distribution?: unknown;
          weight_class_distribution?: unknown;
          fat_class_distribution?: unknown;
          line_items?: unknown;
          realisation_factor?: number | null;
          payment_check_result?: unknown | null;
          source_file_path?: string | null;
          notes?: string | null;
        };
      };
      category_prices: {
        Row: {
          id: string;
          category: string;
          breed: string | null;
          saleyard: string | null;
          state: string | null;
          weight_range: string | null;
          price_per_kg: number;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          category: string;
          breed?: string | null;
          saleyard?: string | null;
          state?: string | null;
          weight_range?: string | null;
          price_per_kg: number;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          category?: string;
          breed?: string | null;
          saleyard?: string | null;
          state?: string | null;
          weight_range?: string | null;
          price_per_kg?: number;
          updated_at?: string;
          created_at?: string;
        };
      };
      breed_premiums: {
        Row: {
          id: string;
          breed: string;
          species: string;
          premium_percent: number;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          breed: string;
          species: string;
          premium_percent: number;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          breed?: string;
          species?: string;
          premium_percent?: number;
          updated_at?: string;
          created_at?: string;
        };
      };
      saved_freight_estimates: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          herd_id: string | null;
          app_category: string;
          sex: string;
          average_weight_kg: number;
          head_count: number;
          distance_km: number;
          rate_per_deck_per_km: number;
          freight_category_id: string;
          freight_category_name: string;
          capacity_source: string;
          heads_per_deck: number;
          decks_required: number;
          has_partial_deck: boolean;
          spare_spots_on_last_deck: number;
          total_cost: number;
          cost_per_head: number;
          cost_per_deck: number;
          cost_per_km: number;
          category_warning: string | null;
          breeder_auto_detect_notice: string | null;
          efficiency_prompt: string | null;
          is_custom_job: boolean;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          herd_id?: string | null;
          app_category: string;
          sex: string;
          average_weight_kg: number;
          head_count: number;
          distance_km: number;
          rate_per_deck_per_km: number;
          freight_category_id: string;
          freight_category_name: string;
          capacity_source?: string;
          heads_per_deck: number;
          decks_required: number;
          has_partial_deck?: boolean;
          spare_spots_on_last_deck?: number;
          total_cost: number;
          cost_per_head: number;
          cost_per_deck: number;
          cost_per_km: number;
          category_warning?: string | null;
          breeder_auto_detect_notice?: string | null;
          efficiency_prompt?: string | null;
          is_custom_job?: boolean;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          herd_id?: string | null;
          app_category?: string;
          sex?: string;
          average_weight_kg?: number;
          head_count?: number;
          distance_km?: number;
          rate_per_deck_per_km?: number;
          freight_category_id?: string;
          freight_category_name?: string;
          capacity_source?: string;
          heads_per_deck?: number;
          decks_required?: number;
          has_partial_deck?: boolean;
          spare_spots_on_last_deck?: number;
          total_cost?: number;
          cost_per_head?: number;
          cost_per_deck?: number;
          cost_per_km?: number;
          category_warning?: string | null;
          breeder_auto_detect_notice?: string | null;
          efficiency_prompt?: string | null;
          is_custom_job?: boolean;
          notes?: string | null;
        };
      };
      consignments: {
        Row: {
          id: string;
          user_id: string;
          consignment_name: string | null;
          processor_name: string;
          plant_location: string | null;
          booking_reference: string | null;
          kill_date: string | null;
          status: "draft" | "confirmed" | "completed";
          total_head_count: number | null;
          total_gross_value: number | null;
          total_net_value: number | null;
          processor_grid_id: string | null;
          kill_sheet_record_id: string | null;
          notes: string | null;
          is_deleted: boolean;
          deleted_at: string | null;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          consignment_name?: string | null;
          processor_name: string;
          plant_location?: string | null;
          booking_reference?: string | null;
          kill_date?: string | null;
          status?: "draft" | "confirmed" | "completed";
          total_head_count?: number | null;
          total_gross_value?: number | null;
          total_net_value?: number | null;
          processor_grid_id?: string | null;
          kill_sheet_record_id?: string | null;
          notes?: string | null;
          is_deleted?: boolean;
        };
        Update: {
          consignment_name?: string | null;
          processor_name?: string;
          plant_location?: string | null;
          booking_reference?: string | null;
          kill_date?: string | null;
          status?: "draft" | "confirmed" | "completed";
          total_head_count?: number | null;
          total_gross_value?: number | null;
          total_net_value?: number | null;
          processor_grid_id?: string | null;
          kill_sheet_record_id?: string | null;
          notes?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
        };
      };
      consignment_allocations: {
        Row: {
          id: string;
          consignment_id: string;
          herd_id: string;
          head_count: number;
          category: string | null;
          average_weight: number | null;
          total_value: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          consignment_id: string;
          herd_id: string;
          head_count: number;
          category?: string | null;
          average_weight?: number | null;
          total_value?: number | null;
        };
        Update: {
          head_count?: number;
          category?: string | null;
          average_weight?: number | null;
          total_value?: number | null;
        };
      };
      brangus_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          preview_text: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          preview_text?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
          deleted_at?: string | null;
        };
        Update: {
          title?: string | null;
          preview_text?: string | null;
          updated_at?: string;
          is_deleted?: boolean;
          deleted_at?: string | null;
        };
      };
      brangus_messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          created_at: string;
          cards_json: unknown[] | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          created_at?: string;
          cards_json?: unknown[] | null;
        };
        Update: {
          content?: string;
          cards_json?: unknown[] | null;
        };
      };
    };
  };
};

// Convenience type aliases
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
